# ECS784: Part of Lab 2

# Some basic programming exercises on numpy

In [1]:
import numpy as np

#### 1. Create a vector 'int_vector' (1 dimensional array) and fill it with 10 random integers.

In [2]:
int_vector = np.random.randint(10, 100, 10) # returns 10 random integers between 10 and 100
print(int_vector)

[96 23 51 62 90 84 35 47 85 91]


#### 2. Create a vector 'rand_vector' and fill it with 10 random values ranging between 0 and 1

In [3]:
rand_vector = np.random.rand((10))
print(rand_vector)

[0.76712785 0.29490787 0.01759973 0.46029058 0.51081097 0.7936829
 0.59700347 0.05255189 0.6722148  0.88393551]


#### 3. Find the smallest and largest elements in int_vector created at step 1. 
 * Do this with and without using the numpy in-built function.
 

In [4]:
def max_min(data):
    """
    Find the maximum and minimum elements in a vector without using any in-built function
    """

    large = small = data[0] # retrieve the first element as a reference
    for i in range(1, len(data)):
        if data[i] > large:
            large = data[i]
        if data[i] < small:
            small = data[i]
    
    return large, small

def max_min_2(data):
    """
    Find the maximum and minimum elements in a vector using in-built function
    """
    return np.max(data), np.min(data)

In [5]:
# Call the manual based max_min function
max_min(int_vector)

(96, 23)

In [6]:
# Call the in-built-based function
max_min_2(int_vector)

(96, 23)

#### 4. Create a vector 'vect1' with 9 elements equally spaced between 10 and 100  

In [7]:
vect1 = np.linspace(10, 100, 9)
print(vect1)

[ 10.    21.25  32.5   43.75  55.    66.25  77.5   88.75 100.  ]


#### 5. Create a 4x4 matrix 'mat1' that has 1 in its diagonal entries and 0 in the remaining entries.

In [8]:
mat1 = np.diag((1, 1, 1, 1))
print(mat1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [9]:
# Or, we could also do it this way
mat1_a = np.eye(4)
print(mat1_a) # However, the default data type here is float not integer

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 6. Create a 5x5 matrix 'mat2' that is populated with random numbers ranging between 0 and 1

In [10]:
mat2 = np.random.rand(5, 5)
print(mat2)

[[0.36667614 0.13147992 0.78687303 0.68556386 0.54825461]
 [0.61154107 0.13643413 0.22570061 0.96150592 0.59082773]
 [0.70950815 0.10343735 0.19288141 0.12530379 0.06576769]
 [0.9064176  0.47724466 0.49253866 0.12878909 0.57737878]
 [0.65507166 0.57956365 0.7080379  0.47421799 0.31329092]]


#### 7. Save the contents of 'mat2' into a CSV file called 'mat2.csv'. Preserve 6 values after the decimal point. Then, read the contents of the CSV file 'mat2.csv' and print its contents.

In [11]:
# save with 6 decimal points
np.savetxt("mat2.csv", mat2, delimiter=",", fmt="%.6f")

In [12]:
# Read the contents of the CSV file into mat2_data
mat2_data = np.genfromtxt("mat2.csv", delimiter=",")

In [13]:
# Print the contents of mat2_data
print(mat2_data)

[[0.366676 0.13148  0.786873 0.685564 0.548255]
 [0.611541 0.136434 0.225701 0.961506 0.590828]
 [0.709508 0.103437 0.192881 0.125304 0.065768]
 [0.906418 0.477245 0.492539 0.128789 0.577379]
 [0.655072 0.579564 0.708038 0.474218 0.313291]]


#### 8. Define a function called 'operation' that takes three inputs: data1, data2 and operationType
 * data1 and data2 can be a scalar, vector or matrix.
 * operationType should be a string.
 * The function should expect one of the following as an input for operationType: "add", "subtract", "multiply", "divide".
 * It should then perform the given operation.

In [14]:
def operation(data1, data2, operationType):

    if operationType == 'add':
        result = data1 + data2
    elif operationType == 'subtract':
        result = data1 - data2
    elif operationType == 'multiply':
        result = data1 * data2
    elif operationType == 'divide':
        result = data1 / data2
    return result

#### 9. Test the function 'operation' for different operations (say, add, multiply) on the following inputs 
 * Two vectors 'rand_v1' and 'rand_v2' containing four random elements between 1 and 10, and 1 and 50 respectively.
 * Call the function this way: operation(rand_v1, rand_v2, 'add')
 * Print the two vectors along with the result of the operation.

In [15]:
# testing addition
rand_v1 = np.random.randint(1, 10, 4)
rand_v2 = np.random.randint(1, 50, 4)
result = operation(rand_v1, rand_v2, 'add')

print(rand_v1)
print(rand_v2)

print(result)

[9 1 4 1]
[23 13 31 24]
[32 14 35 25]


#### 10. Create a numpy vector comprising of 25 elements randomly drawn from a standard normal distribution. Then, convert it into a two dimensional 5 x 5 matrix called 'mat5x5' and print the matrix. 


In [16]:
mat5x5 = np.random.standard_normal(25).reshape(5, 5)
print(mat5x5)

[[ 1.01287159  2.13089114 -0.93684057 -0.73510377 -0.94591583]
 [-0.63055043  0.13056045 -0.23137938 -0.56875446  1.41355133]
 [ 0.19286896 -0.88437818 -0.72097533 -0.35339192  0.11666879]
 [-1.15818788  1.43935773 -0.49086781  0.08538834  0.48100115]
 [ 1.011208    1.6340039  -1.82316859  0.44953958 -0.60802615]]


In [17]:
# check if it is a two dimensional 5 x 5 matrix
print(mat5x5.shape)

(5, 5)


#### 11. Compute the following statistics for the matrix mat5x5:
 * a) Global mean and mean across each dimension
 * b) Global variance and variance across each dimension
 

In [18]:
# Global mean and mean across each dimension
global_mean = np.mean(mat5x5)
print('Global mean: ', global_mean)

dimension_mean = np.mean(mat5x5, axis = 0)
print('Mean across each dimension\n ', dimension_mean)

Global mean:  0.00041482529076763085
Mean across each dimension
  [ 0.08564205  0.89008701 -0.84064634 -0.22446445  0.09145586]


In [19]:
# Global variance and variance across each dimension
global_var = np.var(mat5x5)
print('Global variance: ', global_var)

dimension_var = np.var(mat5x5, axis = 0)
print('Variance across each dimension \n', dimension_var)

Global variance:  0.9451123039142526
Variance across each dimension 
 [0.75759382 1.22406257 0.29649514 0.18924012 0.69314655]
