# ECS784: Part of Lab 2

# Some basic programming exercises on numpy

In [8]:
import numpy as np

#### 1. Create a vector 'int_vector' (1 dimensional array) and fill it with 10 random integers.

In [9]:
int_vector = np.random.randint(10, 100, 10) # returns 10 random integers between 10 and 100
print(int_vector)

[14 94 76 86 95 38 68 13 47 37]


#### 2. Create a vector 'rand_vector' and fill it with 10 random values ranging between 0 and 1

In [10]:
rand_vector = np.random.rand((10))
print(rand_vector)

[0.08605797 0.13592388 0.16547407 0.96524552 0.11642145 0.05613101
 0.0854547  0.28453268 0.31734679 0.3126877 ]


#### 3. Find the smallest and largest elements in int_vector created at step 1. 
 * Do this with and without using the numpy in-built function.
 

In [11]:
def max_min(data):
    """
    Find the maximum and minimum elements in a vector without using any in-built function
    """

    large = small = data[0] # retrieve the first element as a reference
    for i in range(1, len(data)):
        if data[i] > large:
            large = data[i]
        if data[i] < small:
            small = data[i]
    
    return large, small

def max_min_2(data):
    """
    Find the maximum and minimum elements in a vector using in-built function
    """
    return np.max(data), np.min(data)

In [12]:
# Call the manual based max_min function
max_min(int_vector)

(np.int64(95), np.int64(13))

In [13]:
# Call the in-built-based function
max_min_2(int_vector)

(np.int64(95), np.int64(13))

#### 4. Create a vector 'vect1' with 9 elements equally spaced between 10 and 100  

In [14]:
vect1 = np.linspace(10, 100, 9)
print(vect1)

[ 10.    21.25  32.5   43.75  55.    66.25  77.5   88.75 100.  ]


#### 5. Create a 4x4 matrix 'mat1' that has 1 in its diagonal entries and 0 in the remaining entries.

In [18]:
mat1 = np.diag((1, 1, 1, 1))
print(mat1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [19]:
# Or, we could also do it this way
mat1_a = np.eye(4)
print(mat1_a) # However, the default data type here is float not integer

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 6. Create a 5x5 matrix 'mat2' that is populated with random numbers ranging between 0 and 1

In [20]:
mat2 = np.random.rand(5, 5)
print(mat2)

[[0.02688209 0.26070841 0.45621717 0.25522303 0.95126716]
 [0.27194861 0.75109352 0.72519427 0.92804602 0.30439634]
 [0.14919743 0.51597231 0.13905772 0.92402331 0.08259431]
 [0.98307845 0.41632572 0.41529539 0.62542823 0.35631551]
 [0.91953573 0.07807184 0.35966339 0.85559806 0.59079721]]


#### 7. Save the contents of 'mat2' into a CSV file called 'mat2.csv'. Preserve 6 values after the decimal point. Then, read the contents of the CSV file 'mat2.csv' and print its contents.

In [21]:
# save with 6 decimal points
np.savetxt("mat2.csv", mat2, delimiter=",", fmt="%.6f")

In [22]:
# Read the contents of the CSV file into mat2_data
mat2_data = np.genfromtxt("mat2.csv", delimiter=",")

In [23]:
# Print the contents of mat2_data
print(mat2_data)

[[0.026882 0.260708 0.456217 0.255223 0.951267]
 [0.271949 0.751094 0.725194 0.928046 0.304396]
 [0.149197 0.515972 0.139058 0.924023 0.082594]
 [0.983078 0.416326 0.415295 0.625428 0.356316]
 [0.919536 0.078072 0.359663 0.855598 0.590797]]


#### 8. Define a function called 'operation' that takes three inputs: data1, data2 and operationType
 * data1 and data2 can be a scalar, vector or matrix.
 * operationType should be a string.
 * The function should expect one of the following as an input for operationType: "add", "subtract", "multiply", "divide".
 * It should then perform the given operation.

In [24]:
def operation(data1, data2, operationType):

    if operationType == 'add':
        result = data1 + data2
    elif operationType == 'subtract':
        result = data1 - data2
    elif operationType == 'multiply':
        result = data1 * data2
    elif operationType == 'divide':
        result = data1 / data2
    return result

#### 9. Test the function 'operation' for different operations (say, add, multiply) on the following inputs 
 * Two vectors 'rand_v1' and 'rand_v2' containing four random elements between 1 and 10, and 1 and 50 respectively.
 * Call the function this way: operation(rand_v1, rand_v2, 'add')
 * Print the two vectors along with the result of the operation.

In [25]:
# testing addition
rand_v1 = np.random.randint(1, 10, 4)
rand_v2 = np.random.randint(1, 50, 4)
result = operation(rand_v1, rand_v2, 'add')

print(rand_v1)
print(rand_v2)

print(result)

[6 3 2 7]
[41 20  6  6]
[47 23  8 13]


#### 10. Create a numpy vector comprising of 25 elements randomly drawn from a standard normal distribution. Then, convert it into a two dimensional 5 x 5 matrix called 'mat5x5' and print the matrix. 


In [27]:
mat5x5 = np.random.standard_normal(25).reshape(5, 5)
print(mat5x5)

[[-0.72866449  0.88470443 -0.65991183  1.28289     0.42219623]
 [-0.26896997 -0.03273378 -0.29740393 -0.78783393  0.47590292]
 [ 0.14686553  0.15305666  0.27981749  1.20313249  0.51177502]
 [-1.36232984 -0.36634883  0.38579683 -1.00384523 -0.3247379 ]
 [-0.53736416 -1.07972285 -0.31312937 -0.64394218  0.76198413]]


In [28]:
# check if it is a two dimensional 5 x 5 matrix
print(mat5x5.shape)

(5, 5)


#### 11. Compute the following statistics for the matrix mat5x5:
 * a) Global mean and mean across each dimension
 * b) Global variance and variance across each dimension
 

In [29]:
# Global mean and mean across each dimension
global_mean = np.mean(mat5x5)
print('Global mean: ', global_mean)

dimension_mean = np.mean(mat5x5, axis = 0)
print('Mean across each dimension\n ', dimension_mean)

Global mean:  -0.0759526632847731
Mean across each dimension
  [-0.55009259 -0.08820887 -0.12096616  0.01008023  0.36942408]


In [30]:
# Global variance and variance across each dimension
global_var = np.var(mat5x5)
print('Global variance: ', global_var)

dimension_var = np.var(mat5x5, axis = 0)
print('Variance across each dimension \n', dimension_var)

Global variance:  0.48283145649410336
Variance across each dimension 
 [0.25131197 0.41366173 0.15519114 1.02717511 0.13407014]
